# Generated by Django 5.0.6 on 2024-06-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='neighbor',
            name='last_name',
        ),
    ]
