# Generated by Django 5.0.6 on 2024-06-12 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhost', '0002_remove_neighbor_first_name_remove_neighbor_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbor',
            name='last_login',
        ),
    ]
